export const CREATE_ADF_REQUEST = "CREATE_ADF_REQUEST";
export const CREATE_ADF_SUCESS= "CREATE_ADF_SUCESS";
export const CREATE_ADF_FAIL = "CREATE_ADF_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS" ;